# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class ScrapyFrameItem(scrapy.Item):
    # define the fields for your item here like:
    id = scrapy.Field()  #
    entid = scrapy.Field()  #
    jid = scrapy.Field()  # 标准ID
    bzname = scrapy.Field()  # 标准名称
    status = scrapy.Field()  # 标准状态0最新1废止2被更新3被责令停止实施
    bzno = scrapy.Field()  # 标准编号
    bzdate = scrapy.Field()  # 公开日期
    bzbook = scrapy.Field()  # 厂家承诺书
    ENTNAME = scrapy.Field()  # 机构名称
    UNISCID = scrapy.Field()  # 统一社会信用代码
    faren = scrapy.Field()  # 法定代表人
    postcode = scrapy.Field()  # 邮政编码
    dom = scrapy.Field()  # 注册地址
    region = scrapy.Field()  # 行政区划
    wenbenurl = scrapy.Field()  # 查看文本
    weburl = scrapy.Field()  # 页面
    update = scrapy.Field()  #
    name = scrapy.Field()
    attach = scrapy.Field()
    rtype = scrapy.Field()
    title = scrapy.Field()
    code = scrapy.Field()
    short_name = scrapy.Field()
    trade_name = scrapy.Field()
    org_name = scrapy.Field()
    grade_type = scrapy.Field()
    report_date = scrapy.Field()
    url = scrapy.Field()
    url_md5 = scrapy.Field()
    pdf_url = scrapy.Field()
    pdf_path = scrapy.Field()
    table_name = scrapy.Field()  #数据库指定表名
    entid = scrapy.Field()  #
    ENTNAME = scrapy.Field()  # 企业名称
    UNISCID = scrapy.Field()  # 统一社会信用代码
    NACAOID = scrapy.Field()  # 组织机构代码
    REGNO = scrapy.Field()  # 工商注册号
    faren = scrapy.Field()  # 法人
    ENTTYPE = scrapy.Field()  # 企业类型
    REGION = scrapy.Field()  # 注册地区
    address = scrapy.Field()  # 地址
    id = scrapy.Field()  #
    cert_type = scrapy.Field()  # 资质类型1建筑业企业资质2勘察资质3招标代理资格4监理资质5设计与施工一体化资质6设计资质7造价咨询资质
    cert_name = scrapy.Field()  # 资质名称
    cert_num = scrapy.Field()  # 证书号
    cert_from = scrapy.Field()  # 资质自
    cert_to = scrapy.Field()  # 资质至
    cert_org = scrapy.Field()  # 颁发机构
    pname = scrapy.Field()  # 工程名称
    unit = scrapy.Field()  # 建设/完成单位
    scope = scrapy.Field()  # 工程规模
    period = scrapy.Field()  # 开工竣工日期
    pstate = scrapy.Field()  # 质量评定结果
    ptype = scrapy.Field()  # 项目类型
    ptech = scrapy.Field()  # 技术指标
    compdate = scrapy.Field()  # 建成时间
    zmr = scrapy.Field()  # 证明人
    pid = scrapy.Field()  # 建筑执业人员专用id
    wnum = scrapy.Field()  # 文号
    cnum = scrapy.Field()  # 诚信记录编号
    ctype = scrapy.Field()  # 处罚类型
    ddate = scrapy.Field()  # 决定日期
    reason = scrapy.Field()  # 事由
    content = scrapy.Field()  # 决定内容
    authorg = scrapy.Field()  # 实施部门
    release = scrapy.Field()  # 发布有效期
    purl = scrapy.Field()  # 个人url
    updated = scrapy.Field()  #
    sex = scrapy.Field()  # 性别
    age = scrapy.Field()  # 年龄
    edu = scrapy.Field()  # 文化程度
    major = scrapy.Field()  # 专业
    workyear = scrapy.Field()  # 工龄
    CERNO = scrapy.Field()  # 证件号码
    CERTYPE = scrapy.Field()  # 证件类型1身份证2护照3港澳台4其他
    sealnum = scrapy.Field()  # 执业印章号
    validity = scrapy.Field()  # 有效期
    gcyjurl = scrapy.Field()  # 个人工程业绩url
    blxwurl = scrapy.Field()  # 不良行为url
    lhxwurl = scrapy.Field()  # 良好行为url
    bgjlurl = scrapy.Field()  # 变更记录url
    ENTNAME_BE = scrapy.Field()  # 变更前企业
    ENTNAME_AF = scrapy.Field()  # 变更后企业
    ALTDATE = scrapy.Field()  # 变更日期
    pnum = scrapy.Field()  # 项目编号
    pregion = scrapy.Field()  # 项目属地
    pvnum = scrapy.Field()  # 省级项目编号
    cuse = scrapy.Field()  # 工程用途01居住建筑02居住建筑配套工程03商业建筑04办公建筑05商住楼06工业建筑07工业建筑配套工程08科教文卫建筑09旅游建筑10农业建筑11农业建筑配套工程12通信建筑13公共建筑14公共建筑配套工程15环境园林16风景园林17公共交通18交通运输类19道路20桥隧21排水22给水23燃气24热力25其他
    captial = scrapy.Field()  # 总投资
    tarea = scrapy.Field()  # 总面积
    plevel = scrapy.Field()  # 立项级别1部级2省级3地市级4区县级
    ztburl = scrapy.Field()  # 招投标url
    sgtscurl = scrapy.Field()  # 施工图审查url
    htbaurl = scrapy.Field()  # 合同备案url
    sgxkurl = scrapy.Field()  # 施工许可url
    jgysbaurl = scrapy.Field()  # 竣工验收备案url
    role = scrapy.Field()  # 角色0建设单位1工程总承包2施工总包,3施工分包,4施工劳务,5专业承包,6监理,7设计,8设计施工一体化,9勘察,10项目管理11施工图审查99其他
    source = scrapy.Field()  # 来源1项目基础2合同备案3竣工验收4施工图审核5施工许可6招投标
    ct_num = scrapy.Field()  # 合同备案号
    ct_hnum = scrapy.Field()  # 省级合同备案号
    ct_bnum = scrapy.Field()  # 合同编号
    ct_type = scrapy.Field()  # 合同类别0建设单位1工程总承包2施工总包,3施工分包,4施工劳务,5专业承包,6监理,7设计,8设计施工一体化,9勘察,10项目管理11施工图审查99其他
    ct_capital = scrapy.Field()  # 合同金额
    ct_scale = scrapy.Field()  # 建设规模
    sdate = scrapy.Field()  # 合同签订日期
    ENTNAME_f = scrapy.Field()  # 发包单位名称
    NACAOID_f = scrapy.Field()  # 发包单位组代
    ENTNAME_c = scrapy.Field()  # 承包单位名称
    NACAOID_c = scrapy.Field()  # 承包单位组代
    ENTNAME_l = scrapy.Field()  # 联合承包单位
    NACAOID_l = scrapy.Field()  # 联合承包单位组代
    indate = scrapy.Field()  # 记录登记时间
    compnum = scrapy.Field()  # 竣工备案号
    compvnum = scrapy.Field()  # 省级竣工备案编号
    rcost = scrapy.Field()  # 实际造价
    rarea = scrapy.Field()  # 实际面积
    rscale = scrapy.Field()  # 实际建设规模
    structure = scrapy.Field()  # 结构体系
    rbdate = scrapy.Field()  # 实际开工日期
    redate = scrapy.Field()  # 实际竣工验收日期
    remark = scrapy.Field()  # 备注
    dnum = scrapy.Field()  # 施工图审查合格证书编号
    dvnum = scrapy.Field()  # 省级施工图审查合格书编码
    ENTNAME_d = scrapy.Field()  # 施工图审查机构
    NACAOID_d = scrapy.Field()  # 施工图审查机构组代
    cdate = scrapy.Field()  # 审查完成日期
    cscale = scrapy.Field()  # 建设规模
    canum = scrapy.Field()  # 施工许可编号
    cavnum = scrapy.Field()  # 省级施工许可编号
    cdnum = scrapy.Field()  # 施工图审查合格编号
    pmanager = scrapy.Field()  # 项目经理
    pmanager_cerno = scrapy.Field()  # 项目经理身份证号
    inspector = scrapy.Field()  # 项目总监
    inspector_cerno = scrapy.Field()  # 项目总监身份证号
    ct_area = scrapy.Field()  # 面积
    bnum = scrapy.Field()  # 中标通知书编号
    bvnum = scrapy.Field()  # 省级中标通知书编号
    btype = scrapy.Field()  # 招标类型0建设单位1工程总承包2施工总包,3施工分包,4施工劳务,5专业承包,6监理,7设计,8设计施工一体化,9勘察,10项目管理11施工图审查99其他
    bway = scrapy.Field()  # 招标方式1直接委托,2公开招标3邀请招标4其他
    bdate = scrapy.Field()  # 中标日期
    bcapital = scrapy.Field()  # 中标金额
    bscale = scrapy.Field()  # 建设规模
    barea = scrapy.Field()  # 面积
    ENTNAME_a = scrapy.Field()  # 招标代理单位
    NACAOID_a = scrapy.Field()  # 招标代理单位组代
    ENTNAME_z = scrapy.Field()  # 中标单位
    NACAOID_z = scrapy.Field()  # 中标单位组代

